STEWARDSHIP_NOTICE = ("Global Music Compass supports preparation and respectful collaboration. It does not replace "
                      "learning directly from musicians, culture-bearers, educators, and communities connected to the tradition.")

AUDIO_NOTICE = ("Pitch and rhythm playback is a synthesized placeholder reference for orientation only. It is NOT an "
                "authoritative recording of the tradition. Reviewed audio examples will replace it.")


def gov(tradition, community, region, permission="educational", sensitivity="Standard educational context",
        reviewer="Pending practitioner review", scholar="Pending scholar review", verified="Demonstration content — not yet verified"):
    return {"tradition": tradition, "community": community, "region": region,
            "practitioner_reviewer": reviewer, "scholar_reviewer": scholar, "review_date": None,
            "source": "Demonstration seed content", "audio_rights": "Synthesized placeholder — no cultural recording used",
            "cultural_sensitivity": sensitivity, "permission_level": permission, "last_verified": verified}


# permission_level: public | educational | restricted | community-controlled
TRADITIONS = [
    {
        "id": "western-tonal", "name": "Western European Tonal & Modal Systems", "short": "Western Tonal",
        "region": "Europe / global", "community": "European art-music lineage and its global inheritors",
        "hero": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "The major/minor tonal system and church modes underpin much Western classical and popular music. It emphasizes functional harmony, equal temperament, and written notation.",
        "pitch_organization": "12 equal-tempered semitones per octave; major/minor scales and modes built on a tonic.",
        "tuning": "Equal temperament (A4≈440Hz); historically other temperaments were used.",
        "tonal_center": "Tonic of the key; harmony gravitates toward it.",
        "systems": "Major, natural/harmonic/melodic minor, and the seven diatonic modes (Ionian…Locrian).",
        "movement": "Stepwise and triadic motion; leading-tone resolution to the tonic.",
        "microtonal": "Generally fixed pitch; microtonality is exceptional, not foundational.",
        "ornamentation": "Trills, mordents, appoggiaturas, grace notes — largely notated.",
        "improvisation": "Central historically (figured bass, cadenzas); today common in jazz-adjacent contexts.",
        "rhythm": "Bar-based meter with strong/weak beats; time signatures.",
        "form": "Sonata, binary, ternary, verse-chorus, theme-and-variations.",
        "ensemble_roles": "Conductor-led orchestras; score defines each part.",
        "notation": "Five-line staff notation, precise and prescriptive.",
        "instruments": ["Piano", "Violin family", "Woodwinds", "Brass"],
        "vocal": "Bel canto and choral traditions; text-driven phrasing.",
        "rehearsal_etiquette": "Punctual, score-based; follow the conductor; mark parts.",
        "performance_context": "Concert halls, recitals, worship, popular stages.",
        "meaning": "Ranges from sacred to secular concert and entertainment settings.",
        "permissions": "Broadly shared repertoire, but respect living composers' rights and editions.",
        "listening": ["J.S. Bach — keyboard works", "Beethoven symphonies", "Contemporary film scores"],
        "glossary": [{"term": "Tonic", "meaning": "Home pitch/chord of a key"}, {"term": "Cadence", "meaning": "Harmonic resolution"}],
        "scales": [
            {"name": "Major (Ionian)", "type": "scale", "tonic": "C", "ascending": [0,2,4,5,7,9,11,12], "descending": [12,11,9,7,5,4,2,0],
             "degrees": ["1","2","3","4","5","6","7","8"], "ornamentation": "Optional trills/turns", "attention": "Leading tone (7) pulls to tonic",
             "western_approx": "This IS the Western reference", "why_not_equivalent": "Reference framework itself."},
            {"name": "Dorian mode", "type": "mode", "tonic": "D", "ascending": [0,2,3,5,7,9,10,12], "descending": [12,10,9,7,5,3,2,0],
             "degrees": ["1","2","♭3","4","5","6","♭7","8"], "ornamentation": "—", "attention": "Raised 6 distinguishes it from natural minor",
             "western_approx": "Minor with a raised 6th", "why_not_equivalent": "A mode, not a separate tuning system."},
        ],
        "gov": gov("Western European tonal system", "European art-music lineage", "Europe / global", permission="public",
                   reviewer="Common-practice pedagogy", scholar="Widely documented", verified="Common musicological reference"),
    },
    {
        "id": "american-gospel", "name": "American Gospel", "short": "Gospel",
        "region": "United States", "community": "Black American church traditions",
        "hero": "https://images.unsplash.com/photo-1508025690966-2a9a1957da31?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "Rooted in Black American church worship, gospel blends call-and-response, blues tonality, rich harmony, and expressive vocal improvisation in a spiritual context.",
        "pitch_organization": "Diatonic with prominent blue notes (flatted 3rd, 5th, 7th) and gospel voicings.",
        "tuning": "Equal temperament; expressive pitch bends in voice.",
        "tonal_center": "Key center with frequent modulation ('taking it up').",
        "systems": "Major/minor with blues inflection; extended and passing chords.",
        "movement": "Stepwise soulful lines; melisma and vocal runs.",
        "microtonal": "Expressive micro-bends in the voice, not a fixed microtonal system.",
        "ornamentation": "Melisma, runs, growls, bends, shouts.",
        "improvisation": "Central — ad-lib vocals, organ fills, spontaneous modulation.",
        "rhythm": "Backbeat, shuffle, and driving 6/8 'gospel' feels; clapping on 2 & 4.",
        "form": "Verse/vamp/'drive'/modulation; often builds to a climactic vamp.",
        "ensemble_roles": "Music director/organist leads; choir + rhythm section respond to cues.",
        "notation": "Often taught by ear; lead sheets/numbers common.",
        "instruments": ["Hammond organ", "Piano", "Bass", "Drums", "Choir"],
        "vocal": "Powerful, expressive lead + responsive choir; testimony-driven.",
        "rehearsal_etiquette": "Learn by ear quickly, watch the MD's hand cues, honor the worship context.",
        "performance_context": "Worship services, concerts, recordings.",
        "meaning": "Sacred worship expression — spiritually significant, not mere entertainment.",
        "permissions": "Respect its worship context and origins; credit arrangers and traditions.",
        "listening": ["Traditional choir gospel", "Contemporary gospel", "Quartet gospel"],
        "glossary": [{"term": "Vamp", "meaning": "Repeated climactic section"}, {"term": "The drive", "meaning": "Intense repeated build"}],
        "scales": [
            {"name": "Gospel/Blues-inflected Major", "type": "scale", "tonic": "C", "ascending": [0,2,3,4,7,9,10,12], "descending": [12,10,9,7,4,3,2,0],
             "degrees": ["1","2","♭3","3","5","6","♭7","8"], "ornamentation": "Bends between ♭3–3", "attention": "The ♭3↔3 'blue' area is expressive, not fixed",
             "western_approx": "Major scale with added blue notes", "why_not_equivalent": "Blue notes are flexible pitch zones sung with micro-bends, not fixed scale steps."},
        ],
        "gov": gov("American gospel", "Black American church traditions", "United States", permission="educational",
                   sensitivity="Sacred worship context — represent respectfully, not as generic 'soul' style."),
    },
    {
        "id": "american-jazz", "name": "American Jazz", "short": "Jazz",
        "region": "United States", "community": "African American improvised-music tradition",
        "hero": "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "An African American art form built on swing, blues, and sophisticated harmony, prizing individual and collective improvisation over changing chord progressions.",
        "pitch_organization": "Chromatic harmony, modes, and blues scales over functional/modal progressions.",
        "tuning": "Equal temperament with expressive blue-note bends.",
        "tonal_center": "Shifts with the chord changes; modal jazz centers on modes.",
        "systems": "Modes, bebop scales, blues scales, altered dominants.",
        "movement": "Guide-tone lines, enclosures, chromatic approach tones.",
        "microtonal": "Blue-note bends in the voice/horns; not a fixed microtonal system.",
        "ornamentation": "Ghost notes, bends, scoops, falls, vibrato.",
        "improvisation": "Central — soloing over 'changes'; trading fours; collective interplay.",
        "rhythm": "Swing feel, syncopation, comping; walking bass; ride-cymbal pulse.",
        "form": "Head–solos–head; 12-bar blues; 32-bar AABA standards.",
        "ensemble_roles": "Bandleader counts off; rhythm section supports soloists; cues by ear/eye.",
        "notation": "Lead sheets (melody + chord symbols); much is aural.",
        "instruments": ["Saxophone", "Trumpet", "Piano", "Double bass", "Drums"],
        "vocal": "Scat improvisation; phrasing 'behind the beat'.",
        "rehearsal_etiquette": "Know the standard, listen hard, trade solos, respect the form.",
        "performance_context": "Clubs, festivals, concert halls, sessions.",
        "meaning": "Artistic expression and dialogue; deep cultural heritage.",
        "permissions": "Credit composers/arrangers; respect the tradition's origins.",
        "listening": ["Bebop recordings", "Modal jazz", "Contemporary jazz"],
        "glossary": [{"term": "Changes", "meaning": "The chord progression"}, {"term": "Comping", "meaning": "Accompanying rhythmically"}],
        "scales": [
            {"name": "Dorian (modal jazz)", "type": "mode", "tonic": "D", "ascending": [0,2,3,5,7,9,10,12], "descending": [12,10,9,7,5,3,2,0],
             "degrees": ["1","2","♭3","4","5","6","♭7","8"], "ornamentation": "Enclosures, chromatic approach", "attention": "Improvise over one mode for long stretches",
             "western_approx": "Dorian mode", "why_not_equivalent": "Functions as an improvisational color, not just a scale to run."},
            {"name": "Blues scale", "type": "scale", "tonic": "C", "ascending": [0,3,5,6,7,10,12], "descending": [12,10,7,6,5,3,0],
             "degrees": ["1","♭3","4","♭5","5","♭7","8"], "ornamentation": "Bends across ♭5", "attention": "♭5 is a passing 'blue' inflection",
             "western_approx": "Minor pentatonic + ♭5", "why_not_equivalent": "The 'blue' pitches are expressive zones, sung/played with bends."},
        ],
        "gov": gov("American jazz", "African American improvised-music tradition", "United States", permission="educational"),
    },
    {
        "id": "hindustani", "name": "Hindustani Classical Music", "short": "Hindustani",
        "region": "North India, Pakistan", "community": "North Indian / South Asian classical lineages (gharanas)",
        "hero": "https://images.unsplash.com/photo-1603048588665-791ca8aea617?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "A North Indian classical tradition organized around raga (melodic framework) and tala (rhythmic cycle), transmitted orally through guru–shishya lineages.",
        "pitch_organization": "Raga: a melodic framework with specific notes (swaras), rules of ascent/descent, and characteristic phrases — far more than a scale.",
        "tuning": "Just-intonation-leaning; tuned relative to a chosen tonic (Sa), often with a drone.",
        "tonal_center": "Sa (the tonic) established by a tanpura/drone throughout.",
        "systems": "Hundreds of ragas, grouped by thaat (parent scales) and time-of-day associations.",
        "movement": "Aroha (ascent) and avaroha (descent) may differ; characteristic pakad (catch-phrase) defines the raga.",
        "microtonal": "Shrutis (microtonal inflections) and meend (glides) are essential — pitch is flexible and expressive.",
        "ornamentation": "Meend, gamak, kan, andolan — ornamentation is intrinsic to the raga's identity.",
        "improvisation": "Central and expansive — alap, jor, jhala, and improvised development within the raga's rules.",
        "rhythm": "Tala: cyclical rhythmic frameworks (e.g., Teentaal=16 beats) with a return point (sam).",
        "form": "Alap (free) → composition (bandish) → rhythmic development; long arcs.",
        "ensemble_roles": "Lead melodic artist, tabla (percussion), tanpura (drone); dialogue with the tabla.",
        "notation": "Primarily oral/aural; sargam syllables (Sa Re Ga Ma…) used as a guide.",
        "instruments": ["Sitar", "Sarod", "Bansuri", "Tabla", "Tanpura", "Voice"],
        "vocal": "Khayal, dhrupad; syllabic sargam and text; central to the tradition.",
        "rehearsal_etiquette": "Respect the guru/lead, tune to Sa first, ask which raga & tala, listen before playing.",
        "performance_context": "Concerts, gharana settings, some devotional contexts.",
        "meaning": "Ragas carry mood (rasa) and time associations; some have devotional weight.",
        "permissions": "Learn ragas respectfully from practitioners; do not treat as generic 'Indian scales'.",
        "listening": ["Vocal khayal", "Sitar/sarod recitals", "Tabla solos"],
        "glossary": [{"term": "Raga", "meaning": "Melodic framework (not just a scale)"}, {"term": "Tala", "meaning": "Rhythmic cycle"}, {"term": "Sam", "meaning": "First beat / return point"}, {"term": "Sa", "meaning": "The tonic"}],
        "scales": [
            {"name": "Raga Yaman", "type": "raga", "tonic": "Sa", "ascending": [0,2,4,6,7,9,11,12], "descending": [12,11,9,7,6,4,2,0],
             "degrees": ["S","R","G","M♯","P","D","N","S"], "ornamentation": "Meend (glides), emphasis on Ga & Ni", "attention": "Uses tivra Ma (sharp 4th); characteristic phrases matter more than the scale",
             "western_approx": "Lydian-like (major with raised 4th)", "why_not_equivalent": "Yaman is defined by phrases, glides, weight on certain swaras and time-of-performance — not by the scale alone. Calling it 'Lydian' misses its identity."},
        ],
        "gov": gov("Hindustani classical", "North Indian classical gharanas", "North India / Pakistan", permission="educational",
                   sensitivity="Do not reduce ragas to Western scales; learn from practitioners."),
    },
    {
        "id": "carnatic", "name": "Carnatic Classical Music", "short": "Carnatic",
        "region": "South India", "community": "South Indian classical tradition",
        "hero": "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "The South Indian classical system, highly systematized around melakarta ragas and complex tala, with a strong devotional and compositional core.",
        "pitch_organization": "Raga with 72 melakarta (parent) ragas and many janya (derived) ragas.",
        "tuning": "Relative to a chosen Sa with a drone; expressive gamaka inflections.",
        "tonal_center": "Sa, held by a drone (tambura/shruti box).",
        "systems": "Melakarta and janya ragas; systematic swara combinations.",
        "movement": "Arohana/avarohana with defining gamakas (oscillations).",
        "microtonal": "Gamaka (oscillating microtonal ornaments) are essential to raga identity.",
        "ornamentation": "Gamaka is central — notes are rarely 'plain'.",
        "improvisation": "Raga alapana, niraval, kalpana swaras — structured improvisation.",
        "rhythm": "Tala system with counting gestures; korvai and complex rhythmic cadences.",
        "form": "Varnam, kriti, alapana, tani avartanam (percussion solo).",
        "ensemble_roles": "Lead vocalist/instrumentalist, violin, mridangam; percussion dialogue.",
        "notation": "Sargam-based; largely oral with written kritis.",
        "instruments": ["Veena", "Violin", "Mridangam", "Ghatam", "Voice"],
        "vocal": "Composition-centered; devotional texts common.",
        "rehearsal_etiquette": "Confirm raga & tala, tune to Sa, respect the composition and its language.",
        "performance_context": "Concerts (kutcheri), temples, festivals.",
        "meaning": "Deep devotional and compositional heritage.",
        "permissions": "Respect devotional context and composers; learn from practitioners.",
        "listening": ["Kriti performances", "Alapana", "Mridangam tani"],
        "glossary": [{"term": "Gamaka", "meaning": "Oscillating ornament essential to a raga"}, {"term": "Kriti", "meaning": "Devotional composition"}],
        "scales": [
            {"name": "Raga Shankarabharanam", "type": "raga", "tonic": "Sa", "ascending": [0,2,4,5,7,9,11,12], "descending": [12,11,9,7,5,4,2,0],
             "degrees": ["S","R2","G3","M1","P","D2","N3","S"], "ornamentation": "Gamaka on most swaras", "attention": "Sounds 'major' but gamakas define it",
             "western_approx": "Resembles the major scale", "why_not_equivalent": "Without gamaka it is not Shankarabharanam; the ornamentation is the raga, not decoration."},
        ],
        "gov": gov("Carnatic classical", "South Indian classical tradition", "South India", permission="educational",
                   sensitivity="Do not equate ragas with Western scales; gamaka is essential."),
    },
    {
        "id": "arabic-maqam", "name": "Arabic Maqam", "short": "Maqam",
        "region": "Arab world (SWANA)", "community": "Arab musical traditions across the region",
        "hero": "https://images.unsplash.com/photo-1516280440614-37939bbacd81?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "A modal system of the Arab world built from ajnas (tetrachord/pentachord fragments), including quarter-tone intervals absent from Western tuning.",
        "pitch_organization": "Maqamat built from ajnas; includes notes between the Western semitones (quarter tones).",
        "tuning": "Not equal temperament — uses microtonal intervals; tuned relative to a tonic.",
        "tonal_center": "Tonic (qarar) with characteristic resting tones.",
        "systems": "Maqamat (e.g., Rast, Bayati, Hijaz, Saba, Nahawand), each with a modulation map.",
        "movement": "Sayr — the typical melodic path and modulations through ajnas.",
        "microtonal": "Quarter tones are foundational, not optional; central to identity.",
        "ornamentation": "Tremolo, slides, expressive microtonal inflection.",
        "improvisation": "Taqsim — improvised exploration of a maqam and its modulations.",
        "rhythm": "Iqa'at — rhythmic modes (e.g., Maqsum, Baladi) with dum/tak strokes.",
        "form": "Taqsim, muwashshah, layali, instrumental/vocal suites.",
        "ensemble_roles": "Takht ensemble; melodic heterophony; lead sets the maqam and sayr.",
        "notation": "Aural transmission; special signs (half-flat/half-sharp) when written.",
        "instruments": ["Oud", "Qanun", "Nay", "Riq", "Violin", "Voice"],
        "vocal": "Highly ornamented, microtonal, text-expressive.",
        "rehearsal_etiquette": "Ask the maqam and sayr, tune carefully (quarter tones), follow the lead's modulations.",
        "performance_context": "Concerts, celebrations, some devotional/spiritual settings.",
        "meaning": "Maqamat can carry emotional and sometimes spiritual associations.",
        "permissions": "Respect regional/communal variation; do not flatten quarter tones to Western pitches.",
        "listening": ["Oud taqsim", "Classical Arab vocal", "Takht ensemble"],
        "glossary": [{"term": "Maqam", "meaning": "Melodic mode with microtones"}, {"term": "Jins", "meaning": "Tetra/pentachord building block"}, {"term": "Taqsim", "meaning": "Improvisation"}, {"term": "Iqa'", "meaning": "Rhythmic mode"}],
        "scales": [
            {"name": "Maqam Rast", "type": "maqam", "tonic": "C", "ascending": [0,2,3.5,5,7,9,10.5,12], "descending": [12,10.5,9,7,5,3.5,2,0],
             "degrees": ["Rast","","half-flat 3","","","","half-flat 7",""], "ornamentation": "Microtonal inflection on the half-flat degrees", "attention": "The 3rd and 7th are ~quarter-tone lowered — between the piano keys",
             "western_approx": "Roughly a major scale with lowered 3rd & 7th", "why_not_equivalent": "The quarter-tone 3rd and 7th do NOT exist on a piano; approximating with E♭ or E natural changes the maqam entirely."},
            {"name": "Maqam Hijaz", "type": "maqam", "tonic": "D", "ascending": [0,1,4,5,7,8,10,12], "descending": [12,10,8,7,5,4,1,0],
             "degrees": ["1","♭2","3","4","5","♭6","♭7","8"], "ornamentation": "Expressive slides across the augmented 2nd", "attention": "Augmented 2nd between ♭2 and 3",
             "western_approx": "Similar to Phrygian dominant", "why_not_equivalent": "Sayr (melodic path) and microtonal shading differ; the label 'Phrygian dominant' is only an entry point."},
        ],
        "gov": gov("Arabic maqam", "Arab musical traditions (SWANA)", "Arab world", permission="educational",
                   sensitivity="Quarter tones are foundational; do not approximate to piano pitches as if equivalent."),
    },
    {
        "id": "west-african", "name": "West African Rhythmic & Ensemble Traditions", "short": "West African",
        "region": "West Africa", "community": "Specific communities (e.g., Ewe, Yoruba, Mandé) — not a single 'African' style",
        "hero": "https://images.unsplash.com/photo-1526218626217-dc65a29bb444?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "Diverse community traditions built on interlocking polyrhythm, call-and-response, and drum/dance ensembles — each community distinct. This is an overview, NOT one 'African rhythm'.",
        "pitch_organization": "Varies by tradition; often pentatonic/heptatonic vocal lines over percussion.",
        "tuning": "Varies; often relative/expressive rather than equal-tempered.",
        "tonal_center": "Community- and song-specific.",
        "systems": "Language- and community-specific melodic practices; talking-drum tonal speech.",
        "movement": "Call-and-response melodic phrases.",
        "microtonal": "Expressive, community-specific pitch practices.",
        "ornamentation": "Vocal and drum inflection; talking-drum pitch bends.",
        "improvisation": "Lead-drummer variation and signal calls within the ensemble.",
        "rhythm": "Interlocking polyrhythm and cross-rhythm over a repeating timeline (bell pattern).",
        "form": "Cyclic, layered; lead drum cues transitions.",
        "ensemble_roles": "Lead drum signals; support drums, bell (gankogui) timeline, dancers integral.",
        "notation": "Oral/aural transmission and embodied learning (drum + dance together).",
        "instruments": ["Djembe", "Dunun", "Gankogui (bell)", "Talking drum", "Shekere"],
        "vocal": "Call-and-response with the ensemble and dancers.",
        "rehearsal_etiquette": "Learn the bell timeline first, watch the lead drummer's signals, respect dance integration.",
        "performance_context": "Ceremonies, community celebrations, concerts — context matters greatly.",
        "meaning": "Many pieces are tied to specific ceremonies/communities and are not context-free.",
        "permissions": "Some repertoire is ceremonial/community-owned — ask before learning/performing/recording.",
        "listening": ["Ewe drum ensembles", "Mandé griot music", "Yoruba drumming"],
        "glossary": [{"term": "Timeline/bell", "meaning": "The organizing repeating pattern"}, {"term": "Polyrhythm", "meaning": "Multiple rhythms sounding together"}],
        "scales": [],
        "gov": gov("West African ensemble traditions", "Specific communities (Ewe, Yoruba, Mandé, etc.)", "West Africa",
                   permission="community-controlled", sensitivity="Do NOT present as one generic 'African rhythm'; some repertoire is ceremonial and community-owned."),
    },
    {
        "id": "afro-cuban", "name": "Afro-Cuban Traditions", "short": "Afro-Cuban",
        "region": "Cuba", "community": "Afro-Cuban communities (incl. sacred Yoruba-derived traditions)",
        "hero": "https://images.unsplash.com/photo-1518972559570-7cc1309f3229?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "Afro-Cuban music spans popular (son, rumba, salsa) and sacred (batá/Santería) traditions, organized around clave and layered percussion.",
        "pitch_organization": "Diatonic popular harmony; sacred chants are call-and-response.",
        "tuning": "Equal temperament in popular music; drums tuned by tradition.",
        "tonal_center": "Song key; montuno vamps.",
        "systems": "Popular harmony; sacred toques (rhythms for specific orishas).",
        "movement": "Montuno riffs; soneo (improvised vocal) call-and-response.",
        "microtonal": "Not central in popular forms.",
        "ornamentation": "Vocal soneo, percussion fills.",
        "improvisation": "Soneo, instrumental solos over montuno.",
        "rhythm": "Clave (2-3 / 3-2) is the organizing key; layered congas, bongó, timbales.",
        "form": "Son/salsa: cuerpo then montuno/coro; rumba structures.",
        "ensemble_roles": "Clave governs everyone; singer leads coro call-and-response.",
        "notation": "Charts for popular music; sacred repertoire is oral.",
        "instruments": ["Congas", "Bongó", "Timbales", "Clave", "Batá (sacred)", "Tres"],
        "vocal": "Lead soneo + coro (chorus) response.",
        "rehearsal_etiquette": "Find the clave direction first (2-3 vs 3-2), lock to it, respect sacred repertoire boundaries.",
        "performance_context": "Dance floors, concerts, and — for batá — sacred ceremonies.",
        "meaning": "Batá/Santería repertoire is sacred and often restricted.",
        "permissions": "Sacred toques may be restricted — do not perform/record without permission.",
        "listening": ["Son cubano", "Rumba", "Salsa"],
        "glossary": [{"term": "Clave", "meaning": "The 2-3/3-2 organizing pattern"}, {"term": "Montuno", "meaning": "Repeated vamp section"}],
        "scales": [],
        "gov": gov("Afro-Cuban traditions", "Afro-Cuban communities", "Cuba", permission="educational",
                   sensitivity="Sacred batá/Santería repertoire is community-controlled and often restricted."),
    },
    {
        "id": "japanese", "name": "Japanese Traditional & Contemporary Music", "short": "Japanese",
        "region": "Japan", "community": "Japanese classical (gagaku, hōgaku) and contemporary practice",
        "hero": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "context": "From courtly gagaku and shakuhachi/koto traditions to a highly advanced contemporary studio scene, Japanese music values space (ma), timbre, and precision.",
        "pitch_organization": "Traditional scales (e.g., in-scale, yo-scale) alongside Western tonality in contemporary music.",
        "tuning": "Traditional relative tunings; contemporary uses equal temperament.",
        "tonal_center": "Mode-dependent; drone/held tones in some genres.",
        "systems": "In (semitone-inflected) and yo (anhemitonic) pentatonic families.",
        "movement": "Subtle, space-aware phrasing; timbral bends (shakuhachi).",
        "microtonal": "Expressive pitch bending on shakuhachi/shamisen.",
        "ornamentation": "Breath-based bends, portamento, timbral shaping.",
        "improvisation": "Some (honkyoku); much is composed/precise.",
        "rhythm": "Flexible, breath-led time in classical forms; precise in contemporary studio.",
        "form": "Jo-ha-kyū (slow–accelerate–climax) aesthetic pacing.",
        "ensemble_roles": "Lead sets pace; contemporary sessions are conductor/producer-led and punctual.",
        "notation": "Traditional tablatures; Western notation in contemporary work.",
        "instruments": ["Koto", "Shakuhachi", "Shamisen", "Taiko"],
        "vocal": "Nagauta and contemporary vocal styles.",
        "rehearsal_etiquette": "Punctuality is respect; honor 'ma' (space); follow cues precisely.",
        "performance_context": "Concert, theatre (kabuki/noh), studio, popular stages.",
        "meaning": "Some forms have ceremonial/theatrical significance.",
        "permissions": "Respect classical lineages and contemporary rights.",
        "listening": ["Shakuhachi honkyoku", "Koto works", "Contemporary J-pop production"],
        "glossary": [{"term": "Ma", "meaning": "Meaningful space/silence"}, {"term": "Jo-ha-kyū", "meaning": "Slow–build–climax pacing"}],
        "scales": [
            {"name": "In scale (pentatonic)", "type": "scale", "tonic": "D", "ascending": [0,1,5,7,8,12], "descending": [12,8,7,5,1,0],
             "degrees": ["1","♭2","4","5","♭6","8"], "ornamentation": "Portamento/bends", "attention": "Semitone above tonic gives its color",
             "western_approx": "A minor-flavored pentatonic", "why_not_equivalent": "Phrasing, ornament, and 'ma' define the sound as much as the pitches."},
        ],
        "gov": gov("Japanese traditional & contemporary", "Japanese classical and contemporary practice", "Japan", permission="educational"),
    },
]

COMPARISONS = [
    {"id": "jazz-hindustani", "a": "american-jazz", "b": "hindustani",
     "title": "American Jazz Musician Preparing for a Hindustani Collaboration"},
    {"id": "western-maqam", "a": "western-tonal", "b": "arabic-maqam",
     "title": "Western Modes and Arabic Maqam"},
    {"id": "backbeat-westafrican", "a": "american-jazz", "b": "west-african",
     "title": "American Backbeat and West African Rhythmic Structures"},
    {"id": "gospel-carnatic", "a": "american-gospel", "b": "carnatic",
     "title": "Gospel Vocalist Meeting Carnatic Improvisation"},
]

SESSION_PHRASES = [
    {"category": "Tempo", "text": "Let's begin from the second chorus."},
    {"category": "Pitch", "text": "Can we lower the tonal center?"},
    {"category": "Ornamentation", "text": "Please demonstrate the ornamentation."},
    {"category": "Pitch", "text": "Is this pitch fixed or flexible?"},
    {"category": "Rhythm", "text": "Where does the rhythmic cycle begin again?"},
    {"category": "Ensemble", "text": "Should I follow the lead musician or the percussion cue?"},
    {"category": "Improvisation", "text": "Is improvisation expected here?"},
    {"category": "Notation", "text": "Can you sing or play the phrase before I notate it?"},
    {"category": "Cultural", "text": "Is this music appropriate to perform outside its original context?"},
    {"category": "Rights", "text": "Who should be credited for this arrangement?"},
    {"category": "Rights", "text": "Do we have permission to record this session?"},
    {"category": "Dynamics", "text": "Can we bring the dynamics down under the vocal?"},
    {"category": "Form", "text": "Take it from the top of the cycle."},
]

RHYTHMS = [
    {"id": "teentaal", "name": "Teentaal (Hindustani)", "tradition": "hindustani", "cycle": 16, "first_beat": 0,
     "note": "16-beat cycle; sam (beat 1) is the return point.",
     "layers": [
        {"name": "Theka (tabla)", "pattern": [1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0], "syllables": "Dha Dhin Dhin Dha…"},
        {"name": "Claps/wave", "pattern": [1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0], "syllables": "clap clap wave clap"},
     ]},
    {"id": "son-clave", "name": "Son Clave 3-2 (Afro-Cuban)", "tradition": "afro-cuban", "cycle": 16, "first_beat": 0,
     "note": "The clave organizes the entire ensemble; direction (3-2 vs 2-3) matters.",
     "layers": [
        {"name": "Clave", "pattern": [1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0], "syllables": "3-side / 2-side"},
        {"name": "Conga tumbao", "pattern": [0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0], "syllables": "—"},
     ]},
    {"id": "west-african-bell", "name": "Standard Bell Timeline (West African)", "tradition": "west-african", "cycle": 12, "first_beat": 0,
     "note": "A 12-pulse bell timeline anchors interlocking parts. Community-specific — one of many.",
     "layers": [
        {"name": "Gankogui (bell)", "pattern": [1,0,1,0,1,1,0,1,0,1,0,1], "syllables": "—"},
        {"name": "Support drum", "pattern": [1,0,0,1,0,0,1,0,0,1,0,0], "syllables": "—"},
     ]},
    {"id": "backbeat", "name": "American Backbeat", "tradition": "american-jazz", "cycle": 8, "first_beat": 0,
     "note": "Snare on beats 2 & 4 defines the backbeat feel.",
     "layers": [
        {"name": "Kick", "pattern": [1,0,0,0,1,0,0,0], "syllables": "boom"},
        {"name": "Snare (backbeat)", "pattern": [0,0,1,0,0,0,1,0], "syllables": "bap"},
        {"name": "Hi-hat", "pattern": [1,1,1,1,1,1,1,1], "syllables": "ts"},
     ]},
]

INSTRUMENTS = [
    {"id": "oud", "name": "Oud", "local_name": "عود", "region": "Arab world", "tradition": "arabic-maqam", "pronunciation": "ood",
     "family": "Fretless lute", "construction": "Pear-shaped body, short fretless neck", "tuning": "Courses tuned in 4ths (varies)",
     "range": "~2.5 octaves", "role": "Lead melodic / taqsim", "techniques": "Risha (plectrum) tremolo, microtonal slides",
     "ensemble": "Central to the takht ensemble", "recording": "Close mic; capture body resonance", "transport": "Fragile — carry as cabin baggage",
     "significance": "Emblematic of Arab music", "etiquette": "Handle with care; ask before touching another's instrument",
     "restrictions": "None specific; respect the maqam being played", "related": ["Lute", "Bouzouki"],
     "image": "https://images.unsplash.com/photo-1516280440614-37939bbacd81?crop=entropy&cs=srgb&fm=jpg&q=85&w=600",
     "questions": ["Which maqam and sayr?", "Fixed or flexible tuning for this piece?"]},
    {"id": "tabla", "name": "Tabla", "local_name": "तबला", "region": "North India", "tradition": "hindustani", "pronunciation": "TUB-la",
     "family": "Hand drum pair", "construction": "Dayan (treble) + bayan (bass), tuned heads with syahi", "tuning": "Dayan tuned to Sa or Pa",
     "range": "Pitched percussion", "role": "Rhythmic lead & dialogue", "techniques": "Bols (na, tin, dha…), modulating bass with heel",
     "ensemble": "Partners the melodic lead", "recording": "Two mics (dayan/bayan)", "transport": "Protect the tuned heads from cold/impact",
     "significance": "Core of Hindustani rhythm", "etiquette": "Tune to the soloist's Sa; do not overpower",
     "restrictions": "None specific", "related": ["Mridangam", "Pakhawaj"],
     "image": "https://images.unsplash.com/photo-1603048588665-791ca8aea617?crop=entropy&cs=srgb&fm=jpg&q=85&w=600",
     "questions": ["Which tala?", "Where is sam (beat 1)?"]},
    {"id": "koto", "name": "Koto", "local_name": "箏", "region": "Japan", "tradition": "japanese", "pronunciation": "KO-to",
     "family": "Zither", "construction": "Long paulownia body with movable bridges", "tuning": "Movable bridges set the scale",
     "range": "~3 octaves", "role": "Melodic lead / accompaniment", "techniques": "Plucking with picks, pitch bends by pressing left of bridge",
     "ensemble": "Sankyoku (with shakuhachi/shamisen)", "recording": "Capture attack + resonance", "transport": "Large — plan freight/oversize",
     "significance": "Iconic Japanese instrument", "etiquette": "Respect tuning setup; remove shoes in some settings",
     "restrictions": "None specific", "related": ["Guzheng", "Gayageum"],
     "image": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?crop=entropy&cs=srgb&fm=jpg&q=85&w=600",
     "questions": ["Which tuning/scale should the bridges be set to?"]},
    {"id": "djembe", "name": "Djembe", "local_name": "djembe", "region": "West Africa (Mandé)", "tradition": "west-african", "pronunciation": "JEM-beh",
     "family": "Goblet hand drum", "construction": "Carved hardwood shell, goatskin head", "tuning": "Rope-tuned",
     "range": "Bass/tone/slap", "role": "Lead or support in the ensemble", "techniques": "Bass, tone, slap; signal calls",
     "ensemble": "Interlocks with dunun and bell", "recording": "Mind the wide dynamic range", "transport": "Heavy shell — check airline rules",
     "significance": "Tied to specific Mandé communities/occasions", "etiquette": "Learn the timeline first; follow the lead drummer's signals",
     "restrictions": "Some rhythms are tied to specific ceremonies — ask", "related": ["Dunun", "Conga"],
     "image": "https://images.unsplash.com/photo-1526218626217-dc65a29bb444?crop=entropy&cs=srgb&fm=jpg&q=85&w=600",
     "questions": ["Is this rhythm tied to a specific occasion?", "Which community's version is this?"]},
]

CLASSROOM_PATHWAY = {
    "title": "Preparing for Cross-Cultural Music Collaboration",
    "modules": [
        {"id": "m1", "title": "Listening Without Assuming", "summary": "Train your ear to hear a tradition on its own terms before mapping it to what you know."},
        {"id": "m2", "title": "Musical Systems Are Not Exact Equivalents", "summary": "Why a raga, maqam, or makam is not 'the same as' a Western scale."},
        {"id": "m3", "title": "Pitch, Tuning, and Ornamentation", "summary": "Fixed vs flexible pitch, microtones, and ornaments that define identity."},
        {"id": "m4", "title": "Rhythm, Time, and Ensemble Communication", "summary": "Cycles, timelines, clave, and who to follow."},
        {"id": "m5", "title": "Rehearsal Language", "summary": "Ask the right questions; communicate musically across languages."},
        {"id": "m6", "title": "Cultural Context and Permission", "summary": "Sacred, ceremonial, and community-owned music; what to ask."},
        {"id": "m7", "title": "Rights, Credits, and Ethical Collaboration", "summary": "Ownership, attribution, and fair credit."},
        {"id": "m8", "title": "Final Collaboration-Readiness Scenario", "summary": "Apply it all to a realistic scenario."},
    ],
    "faculty_tools": ["Assign a musical-tradition overview", "Build comparative-listening assignments", "Assign rhythm & pitch exercises",
                      "Create international collaboration preparation", "Track lesson completion", "Invite a cultural practitioner/guest educator",
                      "Require a reflection", "Connect preparation to a student trip or project"],
}

ACCESS_TIERS = [
    {"id": "individual", "name": "Passport Individual", "audience": "Solo creatives & students", "price": "Demo",
     "features": ["Music Systems Atlas", "Session Translator", "Scale/Raga/Maqam reference", "Rhythm & Time Lab"]},
    {"id": "creative-pro", "name": "Passport Creative Pro", "audience": "Touring & session professionals", "price": "Demo",
     "features": ["Everything in Individual", "Global Rehearsal Mode", "Knowledge Translator", "Saved projects & credits"]},
    {"id": "team", "name": "Passport Team", "audience": "Bands, companies & media teams", "price": "Demo",
     "features": ["Everything in Pro", "Shared team library", "Group rehearsal plans", "Roster readiness"]},
    {"id": "institution", "name": "Passport Institution", "audience": "Schools & programs (ANCRA)", "price": "Demo",
     "features": ["Everything in Team", "Faculty assignments", "Practitioner review workflow", "Global Music Classroom"]},
]

DEMO_PATHWAYS = [
    {
        "id": "us-to-india", "title": "American musician preparing for a collaboration in India",
        "tradition_id": "hindustani", "cover": "https://images.unsplash.com/photo-1603048588665-791ca8aea617?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "system_overview": "You'll work within raga (melodic framework) and tala (rhythmic cycle). Pitch is relative to Sa and often flexible; ornamentation (meend, gamak) is essential, not decorative.",
        "listening": ["A khayal vocal performance", "A sitar or sarod alap", "A tabla solo in Teentaal"],
        "pitch_reference": "Tune to the chosen Sa first. Expect microtonal shrutis and glides — do not force equal-tempered pitches.",
        "rhythm_reference": "Learn where sam (beat 1) falls in the tala; phrases resolve to sam. Teentaal is 16 beats.",
        "rehearsal_vocab": ["Which raga are we in?", "Which tala, and where is sam?", "Is this pitch fixed or flexible?", "Can you sing the phrase before I notate it?"],
        "etiquette": "Defer to the lead artist and guru lineage; tune before playing; listen through a full cycle before entering.",
        "cultural": "Some ragas carry mood and time-of-day associations; a few have devotional weight.",
        "rights": ["Who is credited for the composition/arrangement?", "Do we have permission to record?"],
        "permissions": "Learn ragas from practitioners; avoid treating them as generic 'Indian scales'.",
        "checklist": ["Tune to Sa", "Identify raga & tala", "Listen to 3 reference performances", "Learn 6 rehearsal phrases", "Confirm credits & recording permission"],
    },
    {
        "id": "us-to-mideast", "title": "American musician preparing for a collaboration in the Middle East",
        "tradition_id": "arabic-maqam", "cover": "https://images.unsplash.com/photo-1516280440614-37939bbacd81?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "system_overview": "You'll work within maqam (modal system with quarter tones). Some notes fall between the piano keys — approximating them changes the maqam.",
        "listening": ["An oud taqsim", "A classical Arab vocal piece", "A takht ensemble recording"],
        "pitch_reference": "Prepare for quarter-tone intervals (e.g., the half-flat 3rd in Rast). If your instrument is fixed-pitch, discuss adaptation with the lead.",
        "rhythm_reference": "Learn the iqa' (rhythmic mode) with its dum/tak strokes; feel the cycle.",
        "rehearsal_vocab": ["Which maqam and sayr?", "Are these quarter tones or semitones?", "Which iqa' are we using?", "Please demonstrate the ornamentation."],
        "etiquette": "Follow the lead's modulations (sayr); tune carefully; listen before entering.",
        "cultural": "Maqamat can carry emotional/spiritual associations; regional variation is significant.",
        "rights": ["Who is credited?", "Do we have permission to record?"],
        "permissions": "Respect regional/communal variation; do not flatten microtones.",
        "checklist": ["Study the target maqam", "Prepare for quarter tones", "Learn the iqa'", "Listen to 3 references", "Confirm credits & recording permission"],
    },
    {
        "id": "india-mideast-to-us", "title": "Indian or Middle Eastern musician preparing for an American recording session",
        "tradition_id": "american-jazz", "cover": "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "system_overview": "American studio/jazz/pop sessions use equal temperament, chord 'changes', lead sheets, and backbeat. Your own system is valued — this orients you to their workflow, not above yours.",
        "listening": ["A jazz standard (head–solos–head)", "A pop session/track", "A gospel-influenced arrangement"],
        "pitch_reference": "Expect fixed equal-tempered pitch and click tracks; blue-note bends are expressive, not microtonal systems.",
        "rhythm_reference": "Feel the backbeat (snare on 2 & 4) and play 'in the pocket' with the click.",
        "rehearsal_vocab": ["Where do we take it from?", "Can we lower the key?", "Are we tracking to a click?", "Who owns the master recording?"],
        "etiquette": "Punctual load-in and downbeats; read the lead sheet/chord symbols; efficient, take-based workflow.",
        "cultural": "Studio culture prizes efficiency and clear roles; credits and splits are discussed up front.",
        "rights": ["Who owns the master?", "How are writing credits and splits divided?", "Is there a session/release agreement?"],
        "permissions": "Clarify ownership and credit before tracking; get session agreements in writing.",
        "checklist": ["Review the chart/changes", "Practice to a click", "Learn 6 session phrases", "Confirm master ownership & splits", "Confirm session agreement"],
    },
]
