DISCLAIMER = ("Requirements and conditions may change. Verify current information with the "
              "appropriate government or authoritative source before traveling.")

DEMO_USER = {
    "id": "maya",
    "name": "Maya Thompson",
    "first_name": "Maya",
    "email": "maya.thompson@ancr.demo",
    "discipline": "Musician",
    "home_country": "United States",
    "citizenship": "United States",
    "preferred_language": "English",
    "languages_spoken": ["English", "Spanish (Conversational)"],
    "avatar": "https://images.unsplash.com/photo-1671163700597-160e18736a4b?crop=entropy&cs=srgb&fm=jpg&q=85&w=400",
    "role": "Student",
    "available_roles": ["Student", "Faculty", "Administrator", "Group Manager"],
    "accessibility_preferences": ["Captions preferred", "Standard text size"],
    "global_readiness_score": 72,
    "ancrid": {
        "ancrid_id": "ANCRID-4471-MTHX",
        "verified": True,
        "verified_profile": True,
        "sso_provider": "ANCRID",
        "connected_at": "2026-01-14",
        "shared_fields": ["identity", "role", "language", "verified_profile"],
        "note": "Identity, role, language and verification are provided by ANCRID (single sign-on). ANCR Passport owns all travel, cultural, translation and safety experiences."
    },
    "passport_doc": {
        "number_masked": "•••••• 4821",
        "country": "United States",
        "expires": "2029-06-30",
        "status": "Valid",
    },
    "emergency_contacts": [
        {"id": "ec1", "name": "Denise Thompson", "relationship": "Mother", "phone_masked": "+1 ••• ••• 7734", "primary": True},
        {"id": "ec2", "name": "Prof. Alan Reyes", "relationship": "Program Lead", "phone_masked": "+1 ••• ••• 2210", "primary": False},
    ],
}

DESTINATIONS = [
    {
        "id": "japan", "country": "Japan", "flag": "🇯🇵", "region": "East Asia",
        "tagline": "Precision, ritual, and a world-class creative industry.",
        "hero": "https://images.unsplash.com/photo-1542051841857-5f90071e7989?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "thumb": "https://images.unsplash.com/photo-1601042879364-f3947d3f9c16?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "match_score": 94, "featured": True,
        "overview": "Japan blends deep tradition with one of the most advanced creative economies on earth. For visiting creatives, success depends on respect for hierarchy, punctuality, and quiet professionalism. Tokyo, Osaka and Kyoto each offer distinct creative ecosystems from world-class recording studios to experimental performance spaces.",
        "major_cities": ["Tokyo", "Osaka", "Kyoto", "Fukuoka", "Sapporo"],
        "languages": ["Japanese"], "currency": "Japanese Yen (JPY, ¥)",
        "timezones": ["JST (UTC+9)"],
        "weather": "October is mild and pleasant, 14–21°C, with occasional rain. Pack layers and a light waterproof jacket.",
        "transportation": "Exceptional rail and metro. An IC card (Suica/Pasmo) works across most transit. Trains are punctual to the minute; taxis are clean but costly.",
        "customs": "Bowing is the standard greeting. Remove shoes indoors and in some studios. Silence on trains is expected. Avoid eating while walking.",
        "greetings": ["Konnichiwa — Hello", "Hajimemashite — Nice to meet you", "Yoroshiku onegaishimasu — I look forward to working with you", "Arigatō gozaimasu — Thank you"],
        "dining_etiquette": "Say 'itadakimasu' before eating. Do not stick chopsticks upright in rice. Slurping noodles is acceptable. Pouring drinks for others is polite.",
        "clothing": "Business-smart and understated. Neutral colors are respected in professional settings. Remove shoes when required.",
        "religion_social": "Shinto and Buddhist customs are woven into daily life. Be quiet and respectful at shrines and temples; follow purification rituals where posted.",
        "tipping": "Tipping is generally not practiced and can cause confusion. Excellent service is the norm without a tip.",
        "photography": "Ask before photographing people. Many venues, temples and studios prohibit photography or filming — always look for signage and request permission.",
        "music_industry": "A massive domestic music market with strong live-house culture, precise studio standards, and highly organized label structures. Punctuality and preparation are essential.",
        "venue_etiquette": "Arrive early for load-in. Follow the stage manager's cues precisely. Audiences are attentive and quiet between songs; applause is warm but reserved.",
        "business_customs": "Exchange business cards (meishi) with both hands and a slight bow; receive and study the card respectfully. Decisions are often consensus-based.",
        "laws_to_understand": ["Strict controls on certain medications (including some common cold and ADHD medicines) — check import rules.", "Zero tolerance for illegal substances.", "Work requires the correct visa status; performing for compensation on a tourist entry is not permitted."],
        "prohibited_conduct": ["Public intoxication that disturbs others", "Unauthorized street performance in some districts", "Bringing restricted medications without a Yakkan Shoumei certificate"],
        "importing": "Instruments and gear generally enter smoothly; carry proof of ownership. Commercial merchandise and high-value equipment may require an ATA Carnet or customs declaration.",
        "emergency_numbers": [{"label": "Police", "number": "110"}, {"label": "Fire / Ambulance", "number": "119"}],
        "embassy": "Contact your home country's embassy in Tokyo for consular support, lost documents, or emergencies.",
        "accessibility": "Major cities are increasingly accessible; large stations have elevators and tactile paving. Older venues may have limited access — confirm in advance.",
        "safety": "Japan is very safe with low crime. Be prepared for earthquakes; know your building's evacuation guidance.",
        "lgbtq": "Same-sex activity is legal. Social attitudes are generally private and reserved; legal recognition of partnerships varies by municipality. Discretion is common but major cities have visible communities.",
        "cities_detail": [
            {"name": "Tokyo", "note": "Global creative capital — studios, live houses, fashion and film."},
            {"name": "Osaka", "note": "Energetic, food-centered, strong comedy and live-music scene."},
            {"name": "Kyoto", "note": "Traditional arts, craft, and contemplative performance spaces."},
        ],
    },
    {
        "id": "ghana", "country": "Ghana", "flag": "🇬🇭", "region": "West Africa",
        "tagline": "Rhythm, hospitality, and a booming creative renaissance.",
        "hero": "https://images.unsplash.com/photo-1613323593608-abc90fec84ff?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "thumb": "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "match_score": 88, "featured": True,
        "overview": "Ghana is a warm, welcoming hub of West African creativity, from Afrobeats and highlife to a fast-growing film and fashion scene. Community, elders, and hospitality are central to creative collaboration.",
        "major_cities": ["Accra", "Kumasi", "Cape Coast", "Tamale"],
        "languages": ["English (official)", "Twi", "Ga", "Ewe", "Dagbani"], "currency": "Ghanaian Cedi (GHS, ₵)",
        "timezones": ["GMT (UTC+0)"],
        "weather": "Warm and humid year-round, 24–32°C. A dry Harmattan season brings dusty winds Dec–Feb.",
        "transportation": "Shared 'tro-tro' minibuses, ride-hailing apps in Accra, and taxis. Traffic can be heavy; plan buffer time.",
        "customs": "Greet with the right hand; the left hand is considered impolite for giving/receiving. Respect for elders is paramount.",
        "greetings": ["Akwaaba — Welcome", "Ɛte sɛn? — How are you? (Twi)", "Medaase — Thank you (Twi)"],
        "dining_etiquette": "Meals are often communal. Wash hands before eating; use the right hand. Accepting food is a sign of respect.",
        "clothing": "Colorful and expressive; modest in rural and religious settings. Vibrant prints are celebrated.",
        "religion_social": "Predominantly Christian with significant Muslim and traditional beliefs. Sundays and Friday prayers shape schedules.",
        "tipping": "A 'dash' (small tip) is appreciated for good service but not mandatory.",
        "photography": "Ask permission, especially at markets, sacred sites, and of individuals. Some historical sites have photography rules.",
        "music_industry": "Afrobeats, highlife, and gospel dominate. Live performance and collaboration are community events; drumming and dance are deeply rooted.",
        "venue_etiquette": "Performances are participatory — audiences sing, dance and respond. Respect the emcee and program flow.",
        "business_customs": "Relationships come first; expect warm small talk before business. Punctuality is flexible but respect for elders' time is key.",
        "laws_to_understand": ["Work/performance requires appropriate authorization.", "Photography of military/government sites is restricted.", "Respect cultural heritage export rules for artifacts."],
        "prohibited_conduct": ["Disrespect toward elders or chiefs", "Photographing sacred sites without permission"],
        "importing": "Carry documentation for instruments and gear. High-value equipment may need declaration; a Carnet helps.",
        "emergency_numbers": [{"label": "Police", "number": "191"}, {"label": "Ambulance", "number": "193"}, {"label": "Fire", "number": "192"}],
        "embassy": "Contact your home country's embassy in Accra for consular assistance.",
        "accessibility": "Accessibility infrastructure is limited outside major hotels and venues; plan ahead and confirm access.",
        "safety": "Generally welcoming and safe; use standard precautions with valuables and at night in unfamiliar areas.",
        "lgbtq": "Same-sex relationships are criminalized and social attitudes are conservative. Travelers should be aware of legal risk and exercise significant caution. Verify current law before travel.",
        "cities_detail": [
            {"name": "Accra", "note": "Coastal capital, epicenter of Afrobeats, fashion and film."},
            {"name": "Kumasi", "note": "Ashanti cultural heartland, traditional arts and craft."},
        ],
    },
    {
        "id": "france", "country": "France", "flag": "🇫🇷", "region": "Western Europe",
        "tagline": "Art, cinema, and centuries of creative prestige.",
        "hero": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "thumb": "https://images.unsplash.com/photo-1431274172761-fca41d930114?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "match_score": 90, "featured": True,
        "overview": "France is a global center for cinema, fashion, fine art and music. Cultural literacy, formality, and language courtesy open doors. The creative sector is well-funded and prestigious.",
        "major_cities": ["Paris", "Lyon", "Marseille", "Cannes", "Bordeaux"],
        "languages": ["French"], "currency": "Euro (EUR, €)",
        "timezones": ["CET (UTC+1)"],
        "weather": "October is cool and often rainy, 8–16°C. Bring layers, a scarf, and an umbrella.",
        "transportation": "Excellent TGV rail and metros. Validate tickets. Strikes can affect transit — keep alternatives in mind.",
        "customs": "Greet with 'Bonjour' before any request. A light handshake in business; 'la bise' (cheek kisses) among acquaintances varies by region.",
        "greetings": ["Bonjour — Hello", "Enchanté(e) — Nice to meet you", "Merci beaucoup — Thank you very much"],
        "dining_etiquette": "Meals are unhurried. Keep hands (not elbows) on the table. Wait for 'bon appétit'. Service is included; small rounding is polite.",
        "clothing": "Understated elegance. Avoid overly casual attire in professional and cultural settings.",
        "religion_social": "Secular (laïcité) is a strong civic value; religion is considered private. Respect this in public discourse.",
        "tipping": "Service compris (included). Rounding up or a few euros for great service is appreciated, not required.",
        "photography": "Generally fine in public; ask for individuals. Some museums restrict flash or filming.",
        "music_industry": "Strong support via quotas and public funding. A vibrant festival circuit; SACEM handles rights. Cannes anchors global film.",
        "venue_etiquette": "Punctual, attentive audiences. Encores are earned. Respect union and technical crew schedules.",
        "business_customs": "Formal address (Monsieur/Madame) and titles matter. Expect intellectual, considered discussion. Lunch meetings are common.",
        "laws_to_understand": ["Work requires proper visa/authorization within the Schengen framework.", "Strong copyright and moral-rights protections for creators.", "Strict rules on public image and privacy."],
        "prohibited_conduct": ["Working without authorization", "Ignoring privacy/image rights when filming people"],
        "importing": "EU customs; a Carnet eases temporary import of professional gear. Carry equipment documentation.",
        "emergency_numbers": [{"label": "Europe-wide Emergency", "number": "112"}, {"label": "Police", "number": "17"}, {"label": "Medical (SAMU)", "number": "15"}],
        "embassy": "Contact your home country's embassy in Paris for consular services.",
        "accessibility": "Good in major cities; some historic venues have limited access. Confirm ahead.",
        "safety": "Safe overall; beware pickpockets in tourist areas and on transit.",
        "lgbtq": "Same-sex marriage is legal and protections are strong. France is broadly accepting, especially in major cities.",
        "cities_detail": [
            {"name": "Paris", "note": "Fashion, art, film and music capital."},
            {"name": "Cannes", "note": "Global film festival and industry hub."},
        ],
    },
    {
        "id": "brazil", "country": "Brazil", "flag": "🇧🇷", "region": "South America",
        "tagline": "Warmth, rhythm, and boundless creative energy.",
        "hero": "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "thumb": "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "match_score": 85, "featured": False,
        "overview": "Brazil is a powerhouse of music, dance and film with deep regional diversity. Warmth, physical expressiveness, and social connection drive creative collaboration.",
        "major_cities": ["São Paulo", "Rio de Janeiro", "Salvador", "Recife"],
        "languages": ["Portuguese"], "currency": "Brazilian Real (BRL, R$)",
        "timezones": ["BRT (UTC−3)"],
        "weather": "October is warm; Rio 20–28°C. Coastal humidity; pack light, breathable clothing.",
        "transportation": "Ride-hailing is widespread and recommended in cities. Metro in São Paulo/Rio; traffic is heavy.",
        "customs": "Warm greetings with handshakes or cheek kisses. Personal space is closer; expect friendliness.",
        "greetings": ["Olá — Hello", "Prazer — Nice to meet you", "Obrigado/Obrigada — Thank you"],
        "dining_etiquette": "Meals are social and lengthy. Use utensils even for finger foods. Sharing is common.",
        "clothing": "Expressive and relaxed; smart-casual for business. Beach and city codes differ sharply.",
        "religion_social": "Predominantly Catholic with vibrant Afro-Brazilian traditions (Candomblé, Umbanda). Respect religious festivals.",
        "tipping": "A 10% service charge is common; extra is optional.",
        "photography": "Ask individuals; be cautious displaying expensive gear in public. Respect favela community guidelines.",
        "music_industry": "Samba, bossa nova, funk, sertanejo and a huge live scene. Collaboration is relational and improvisational.",
        "venue_etiquette": "Energetic, participatory audiences. Shows may start late; embrace flexible timing.",
        "business_customs": "Relationships first; expect warmth and flexibility with time. Face-to-face meetings are valued.",
        "laws_to_understand": ["Work/performance requires proper visa.", "Carry ID; register high-value equipment.", "Strict rules protecting cultural heritage."],
        "prohibited_conduct": ["Displaying valuables openly in some areas", "Filming people without consent"],
        "importing": "Bureaucracy can be slow; a Carnet is strongly recommended for professional gear.",
        "emergency_numbers": [{"label": "Police", "number": "190"}, {"label": "Ambulance (SAMU)", "number": "192"}, {"label": "Fire", "number": "193"}],
        "embassy": "Contact your home country's embassy/consulate in Brasília, São Paulo or Rio.",
        "accessibility": "Variable; major venues improving. Confirm access in advance.",
        "safety": "Exercise caution in cities; use trusted transport at night and avoid displaying valuables.",
        "lgbtq": "Same-sex marriage is legal with strong urban communities; attitudes vary regionally.",
        "cities_detail": [
            {"name": "Rio de Janeiro", "note": "Samba, film, and iconic live venues."},
            {"name": "São Paulo", "note": "Largest creative economy; music and design."},
        ],
    },
    {
        "id": "south-korea", "country": "South Korea", "flag": "🇰🇷", "region": "East Asia",
        "tagline": "Hyper-modern, K-culture powerhouse.",
        "hero": "https://images.unsplash.com/photo-1517154421773-0529f29ea451?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "thumb": "https://images.unsplash.com/photo-1538485399081-7191377e8241?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "match_score": 92, "featured": True,
        "overview": "South Korea leads global pop culture through K-pop, film and gaming. The creative industry is fast, polished, hierarchical and highly professional.",
        "major_cities": ["Seoul", "Busan", "Incheon", "Daegu"],
        "languages": ["Korean"], "currency": "South Korean Won (KRW, ₩)",
        "timezones": ["KST (UTC+9)"],
        "weather": "October is crisp and clear, 10–20°C — one of the best months. Bring light layers.",
        "transportation": "World-class subway and rail; T-money card for transit. Everything is fast and punctual.",
        "customs": "Bow to greet; use two hands when giving/receiving. Age and seniority shape interactions.",
        "greetings": ["Annyeonghaseyo — Hello", "Mannaseo bangapseumnida — Nice to meet you", "Gamsahamnida — Thank you"],
        "dining_etiquette": "Wait for elders to eat first. Pour for others, not yourself. Use two hands to receive drinks.",
        "clothing": "Polished and trend-aware. Neat, modern styling is respected in creative circles.",
        "religion_social": "Mix of Christianity, Buddhism and Confucian social values. Respect hierarchy and etiquette.",
        "tipping": "Not customary and can be refused. Service is included.",
        "photography": "Ask individuals; many venues and idol-related spaces restrict filming.",
        "music_industry": "K-pop's rigorous training and production systems set global standards. Timelines are tight; professionalism is expected.",
        "venue_etiquette": "Highly organized fan culture; follow venue rules strictly. Rehearsals are precise and scheduled.",
        "business_customs": "Exchange cards with two hands. Hierarchy matters; defer to seniority. Group harmony is valued.",
        "laws_to_understand": ["Proper visa required for paid performance/work.", "Strict defamation and privacy laws.", "Controlled substances are treated severely."],
        "prohibited_conduct": ["Unauthorized filming of individuals", "Disrespecting seniority in professional settings"],
        "importing": "Efficient customs; document instruments and gear. Carnet recommended for large productions.",
        "emergency_numbers": [{"label": "Police", "number": "112"}, {"label": "Fire / Ambulance", "number": "119"}],
        "embassy": "Contact your home country's embassy in Seoul for consular support.",
        "accessibility": "Excellent in Seoul; subways and major venues are well equipped.",
        "safety": "Very safe with low crime; standard precautions apply.",
        "lgbtq": "Same-sex activity is legal but there is no marriage recognition; attitudes are conservative though Seoul has visible communities.",
        "cities_detail": [
            {"name": "Seoul", "note": "K-pop, film, gaming and fashion capital."},
            {"name": "Busan", "note": "Coastal city, major international film festival."},
        ],
    },
    {
        "id": "united-kingdom", "country": "United Kingdom", "flag": "🇬🇧", "region": "Western Europe",
        "tagline": "Heritage meets a world-leading creative sector.",
        "hero": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "thumb": "https://images.unsplash.com/photo-1520986606214-8b456906c813?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "match_score": 89, "featured": False,
        "overview": "The UK is a global creative leader in music, theatre, film and design. Politeness, punctuality and dry humor characterize professional life. London is a dense creative hub.",
        "major_cities": ["London", "Manchester", "Glasgow", "Bristol", "Liverpool"],
        "languages": ["English"], "currency": "Pound Sterling (GBP, £)",
        "timezones": ["GMT/BST (UTC+0/+1)"],
        "weather": "October is cool and wet, 7–15°C. Always carry a rain layer.",
        "transportation": "Extensive rail and the London Underground. Oyster/contactless for transit. Mind the gap; queue politely.",
        "customs": "Politeness and queuing are serious. 'Please', 'thank you' and 'sorry' are used liberally.",
        "greetings": ["Hello / Hiya — Hello", "Pleased to meet you", "Cheers — Thanks (informal)"],
        "dining_etiquette": "Standard Western etiquette. Rounds are common at the pub; reciprocate. Table manners are relaxed but polite.",
        "clothing": "Smart-casual to formal depending on setting; weather-appropriate layers essential.",
        "religion_social": "Diverse and largely secular in practice. Respect multicultural communities.",
        "tipping": "10–12.5% in restaurants if service isn't included; not expected in pubs.",
        "photography": "Fine in most public spaces; respect privacy and venue rules.",
        "music_industry": "Legendary live circuit, strong festivals, PRS for rights. Highly professional and union-aware.",
        "venue_etiquette": "Punctual sound checks; respect crew and health-and-safety rules. Audiences are enthusiastic.",
        "business_customs": "Understatement and politeness; humor is common. Punctuality is expected; contracts are precise.",
        "laws_to_understand": ["Post-Brexit work permits/visas required for paid engagements.", "Strong IP and licensing framework.", "Strict health-and-safety rules at venues."],
        "prohibited_conduct": ["Working without the correct visa", "Ignoring venue health-and-safety protocols"],
        "importing": "Post-Brexit customs paperwork applies; a Carnet is often necessary for touring gear.",
        "emergency_numbers": [{"label": "Emergency (all)", "number": "999"}, {"label": "Non-emergency Police", "number": "101"}, {"label": "Non-emergency Medical", "number": "111"}],
        "embassy": "Contact your home country's embassy/high commission in London.",
        "accessibility": "Generally good; some historic venues and older Tube stations have limited step-free access.",
        "safety": "Safe overall; be alert to pickpockets in crowded areas.",
        "lgbtq": "Same-sex marriage is legal with strong protections; broadly accepting.",
        "cities_detail": [
            {"name": "London", "note": "Global hub for music, theatre, film and design."},
            {"name": "Manchester", "note": "Iconic music heritage and thriving scene."},
        ],
    },
]

COURSES = [
    {
        "id": "creative-collaboration-japan",
        "title": "Creative Collaboration in Japan",
        "category": "Cultural Intelligence",
        "destination_id": "japan",
        "level": "Intermediate",
        "estimated_minutes": 45,
        "cover": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "overview": "A practical, respectful guide to collaborating with Japanese creative teams — from studio etiquette and hierarchy to home invitations and consensus-based decisions. Designed for working musicians, producers and performers.",
        "badge": "Japan Ready",
        "lessons": [
            {"id": "l1", "title": "Japanese Greetings & Introductions", "minutes": 8,
             "content": "Learn essential greetings, the meishi (business card) ritual, and how bowing conveys respect. First impressions in Japan are built on humility and preparation."},
            {"id": "l2", "title": "Studio & Rehearsal Etiquette", "minutes": 10,
             "content": "Punctuality is respect: arrive early, follow the engineer's lead, keep the space clean, and remove shoes where required. Silence and focus are valued during takes."},
            {"id": "l3", "title": "Hierarchy & Decision-Making", "minutes": 9,
             "content": "Decisions are often consensus-based (nemawashi). Defer to seniority, avoid putting people on the spot, and allow space for indirect communication."},
            {"id": "l4", "title": "Respectful International Collaboration", "minutes": 9,
             "content": "Credit collaborators generously, clarify ownership early and respectfully, and treat cultural elements as partners rather than resources to extract."},
            {"id": "l5", "title": "Social Invitations & Building Trust", "minutes": 9,
             "content": "Being invited out — or to a home — is a meaningful gesture of trust. Bring a small gift, follow your host's lead, and reciprocate warmth with respect."},
        ],
        "scenario": {
            "prompt": "You are invited to a collaborator's home after a studio session. What should you understand before arriving?",
            "options": [
                {"id": "a", "text": "Arrive exactly on time, bring a small wrapped gift (omiyage), and remove your shoes at the entrance.", "correct": True,
                 "feedback": "Correct. Punctuality, a modest gift offered with both hands, and removing shoes show respect and gratitude for the invitation."},
                {"id": "b", "text": "Arrive fashionably late and bring nothing — it's casual.", "correct": False,
                 "feedback": "Lateness reads as disrespect, and arriving empty-handed misses an important gesture of appreciation."},
                {"id": "c", "text": "Bring your whole team unannounced since you're all collaborators.", "correct": False,
                 "feedback": "A home invitation is personal. Never expand the guest list without asking your host first."},
                {"id": "d", "text": "Keep your shoes on and head straight to the kitchen to help yourself.", "correct": False,
                 "feedback": "Keeping shoes on indoors is a significant faux pas; always follow your host's lead."},
            ],
            "explanation": "A home invitation is a high honor signalling trust. Punctuality, a thoughtful omiyage offered with both hands, removing shoes, and following your host's cues all communicate respect and gratitude."
        },
        "knowledge_check": [
            {"id": "q1", "question": "How should you exchange a business card (meishi)?",
             "options": [{"id": "a", "text": "Toss it across the table", "correct": False},
                         {"id": "b", "text": "With both hands and a slight bow, then study it", "correct": True},
                         {"id": "c", "text": "Put it straight in your back pocket", "correct": False}],
             "feedback": "Offer and receive with both hands, then take a moment to read it — pocketing it immediately is disrespectful."},
            {"id": "q2", "question": "What does 'itadakimasu' express?",
             "options": [{"id": "a", "text": "Gratitude before eating", "correct": True},
                         {"id": "b", "text": "A toast for drinks", "correct": False},
                         {"id": "c", "text": "Goodbye", "correct": False}],
             "feedback": "'Itadakimasu' is said before a meal to express gratitude for the food."},
        ],
    },
    {
        "id": "appreciation-vs-appropriation",
        "title": "Cultural Appreciation vs. Appropriation",
        "category": "Cultural Appreciation vs. Appropriation",
        "destination_id": None,
        "level": "Foundational",
        "estimated_minutes": 30,
        "cover": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
        "overview": "A thoughtful framework for engaging with cultural elements respectfully — sourcing, crediting, compensating, and collaborating rather than extracting.",
        "badge": "Culturally Aware",
        "lessons": [
            {"id": "l1", "title": "Understanding Context & Power", "minutes": 8, "content": "Who holds power in the exchange? Context, consent and reciprocity distinguish appreciation from appropriation."},
            {"id": "l2", "title": "Credit, Consent & Compensation", "minutes": 8, "content": "Name your sources, seek consent from culture-bearers, and ensure fair compensation and collaboration."},
            {"id": "l3", "title": "Sacred vs. Shareable", "minutes": 7, "content": "Some elements are sacred and not for performance or commercial use. Learn to ask and listen."},
        ],
        "scenario": {
            "prompt": "You want to feature a traditional rhythm from your host country in a commercial release. What is the most respectful first step?",
            "options": [
                {"id": "a", "text": "Collaborate with and credit local culture-bearers, seek consent, and agree on fair compensation.", "correct": True, "feedback": "Correct — consent, credit and compensation are the foundation of respectful engagement."},
                {"id": "b", "text": "Sample it quietly; it's public domain anyway.", "correct": False, "feedback": "Assuming public domain skips consent and can cause real harm and legal issues."},
                {"id": "c", "text": "Change it slightly so no one recognizes the source.", "correct": False, "feedback": "Obscuring a source to avoid credit is the opposite of respectful practice."},
            ],
            "explanation": "Respectful engagement centers the people whose culture you're drawing from — through consent, credit, collaboration and compensation."
        },
        "knowledge_check": [
            {"id": "q1", "question": "Which trio best defines respectful cultural engagement?",
             "options": [{"id": "a", "text": "Consent, credit, compensation", "correct": True},
                         {"id": "b", "text": "Speed, secrecy, savings", "correct": False},
                         {"id": "c", "text": "Trend, virality, reach", "correct": False}],
             "feedback": "Consent, credit and compensation keep engagement respectful and reciprocal."},
        ],
    },
]

CATEGORIES = [
    "Cultural Intelligence", "Codes of Ethics", "Professional Conduct", "Business Etiquette",
    "Religious and Social Awareness", "Respectful Communication", "Working with Local Creative Teams",
    "International Audience Engagement", "Cultural Appreciation vs. Appropriation",
    "Representing Your Organization Abroad", "Creative Rights Across Borders",
    "International Safety and Responsibility",
]

DISCIPLINES = ["Musician", "Filmmaker", "Dancer", "Visual Artist", "Fashion Professional",
               "Theatre Professional", "Content Creator", "Educator", "Creative Executive"]

CHECKLIST_CATEGORIES = [
    "Passport", "Visa and Work Authorization", "Health and Insurance", "Emergency Planning",
    "Contracts and Invitation Letters", "Equipment and Customs", "Accessibility",
    "Budget and Currency", "Phone and Connectivity", "Electrical Requirements", "Packing",
    "Cultural Preparation", "Language Preparation", "Professional Conduct",
]

def _ci(cat, title, priority, done=False, discipline=None):
    return {"category": cat, "title": title, "priority": priority, "done": done,
            "due_date": None, "document": None, "reminder": False, "discipline": discipline}

CHECKLIST_ITEMS = [
    _ci("Passport", "Confirm passport is valid 6+ months beyond travel", "required", True),
    _ci("Passport", "Make digital + physical copies of passport photo page", "required", True),
    _ci("Visa and Work Authorization", "Determine correct visa for paid collaboration", "urgent", False),
    _ci("Visa and Work Authorization", "Gather invitation letter from host studio", "urgent", True),
    _ci("Health and Insurance", "Purchase international travel + medical insurance", "required", False),
    _ci("Health and Insurance", "Check medication import rules (Yakkan Shoumei)", "urgent", False, "Musician"),
    _ci("Emergency Planning", "Register trip with home embassy program", "recommended", False),
    _ci("Emergency Planning", "Set up emergency contacts in Passport", "required", True),
    _ci("Contracts and Invitation Letters", "Review collaboration agreement & ownership terms", "required", False),
    _ci("Equipment and Customs", "Prepare gear inventory & proof of ownership", "required", True, "Musician"),
    _ci("Equipment and Customs", "Check if ATA Carnet is needed for instruments", "recommended", False, "Musician"),
    _ci("Accessibility", "Confirm venue & lodging accessibility needs", "recommended", False),
    _ci("Budget and Currency", "Set travel budget & notify bank of travel", "recommended", True),
    _ci("Phone and Connectivity", "Arrange eSIM or international data plan", "recommended", False),
    _ci("Electrical Requirements", "Pack Type A/B plug adapters (Japan 100V)", "recommended", False),
    _ci("Packing", "Pack weather-appropriate layers for October", "recommended", False),
    _ci("Cultural Preparation", "Complete 'Creative Collaboration in Japan' course", "required", False),
    _ci("Language Preparation", "Learn 10 essential Japanese phrases", "recommended", False),
    _ci("Professional Conduct", "Review studio etiquette & punctuality norms", "required", True),
    # discipline-specific extras
    _ci("Equipment and Customs", "Prepare camera gear list & lens declarations", "required", False, "Filmmaker"),
    _ci("Contracts and Invitation Letters", "Confirm filming permits & location releases", "urgent", False, "Filmmaker"),
    _ci("Packing", "Pack performance shoes & floor-safe footwear", "recommended", False, "Dancer"),
    _ci("Equipment and Customs", "Insure and document artworks for transit", "required", False, "Visual Artist"),
]

TRIPS = [
    {
        "id": "tokyo-creative-exchange",
        "title": "Tokyo Creative Exchange",
        "destination_id": "japan",
        "destination": "Tokyo, Japan",
        "purpose": "International Music Collaboration",
        "start_date": "2026-10-18", "end_date": "2026-10-27",
        "travel_type": "Individual traveler connected to a school delegation",
        "group": "ANCRA — Berklee Global Delegation",
        "status": "Preparing", "readiness": 72,
        "cover": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "itinerary": [
            {"day": "Oct 18", "title": "Arrival — Narita → Shibuya", "time": "15:40", "type": "Travel", "detail": "Land at NRT, IC card, transfer to hotel in Shibuya."},
            {"day": "Oct 19", "title": "Orientation & Studio Tour", "time": "10:00", "type": "Meeting", "detail": "Meet host producers, tour the recording studio, sign in."},
            {"day": "Oct 20", "title": "Writing Session — Studio A", "time": "13:00", "type": "Session", "detail": "First collaborative writing session with local team."},
            {"day": "Oct 22", "title": "Rehearsal — Live House", "time": "18:00", "type": "Rehearsal", "detail": "Sound check and rehearsal at Shimokitazawa live house."},
            {"day": "Oct 25", "title": "Showcase Performance", "time": "19:30", "type": "Performance", "detail": "Collaborative showcase — invited industry audience."},
            {"day": "Oct 27", "title": "Departure — Haneda", "time": "11:00", "type": "Travel", "detail": "Check out, transfer to HND, return flight."},
        ],
        "team": [
            {"name": "Prof. Alan Reyes", "role": "Program Lead", "avatar": "https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=entropy&cs=srgb&fm=jpg&q=85&w=200"},
            {"name": "Kenji Watanabe", "role": "Host Producer", "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=85&w=200"},
            {"name": "Sofia Marín", "role": "Delegation Peer", "avatar": "https://images.unsplash.com/photo-1606946370568-27bb6a2d1b90?crop=entropy&cs=srgb&fm=jpg&q=85&w=200"},
        ],
        "expenses": [
            {"label": "Flights", "amount": 1180, "currency": "USD", "category": "Travel"},
            {"label": "Lodging (9 nights)", "amount": 1440, "currency": "USD", "category": "Lodging"},
            {"label": "Local transit", "amount": 120, "currency": "USD", "category": "Transport"},
            {"label": "Meals", "amount": 400, "currency": "USD", "category": "Food"},
        ],
    }
]

NETWORK = [
    {"id": "n1", "type": "Musician", "name": "Kenji Watanabe", "role": "Producer / Studio Owner", "city": "Tokyo", "country": "Japan",
     "genres": ["City Pop", "Electronic"], "verified": True, "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=85&w=300",
     "bio": "Grammy-nominated producer running an independent studio in Shibuya. Open to international collaboration."},
    {"id": "n2", "type": "Musician", "name": "Aiko Tanaka", "role": "Session Vocalist", "city": "Tokyo", "country": "Japan",
     "genres": ["J-Pop", "Jazz"], "verified": True, "avatar": "https://images.unsplash.com/photo-1671163700597-160e18736a4b?crop=entropy&cs=srgb&fm=jpg&q=85&w=300",
     "bio": "Bilingual session vocalist available for studio and live work."},
    {"id": "n3", "type": "Store", "name": "Ochanomizu Guitar Row", "role": "Instrument District", "city": "Tokyo", "country": "Japan",
     "genres": ["Guitars", "Gear"], "verified": True, "avatar": "https://images.unsplash.com/photo-1550985616-10810253b84d?crop=entropy&cs=srgb&fm=jpg&q=85&w=300",
     "bio": "Legendary district of instrument shops for repairs, rentals and rare gear."},
    {"id": "n4", "type": "Show", "name": "Shimokitazawa Live Circuit", "role": "Live House Cluster", "city": "Tokyo", "country": "Japan",
     "genres": ["Indie", "Live"], "verified": True, "avatar": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?crop=entropy&cs=srgb&fm=jpg&q=85&w=300",
     "bio": "Dense cluster of intimate live houses — a hub for indie showcases and collaboration."},
    {"id": "n5", "type": "Store", "name": "Tower Records Shibuya", "role": "Record Store", "city": "Tokyo", "country": "Japan",
     "genres": ["Records", "Retail"], "verified": True, "avatar": "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?crop=entropy&cs=srgb&fm=jpg&q=85&w=300",
     "bio": "Iconic multi-floor record store and occasional in-store performance venue."},
    {"id": "n6", "type": "Musician", "name": "Kwame Mensah", "role": "Afrobeats Drummer", "city": "Accra", "country": "Ghana",
     "genres": ["Afrobeats", "Highlife"], "verified": True, "avatar": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?crop=entropy&cs=srgb&fm=jpg&q=85&w=300",
     "bio": "Percussionist and bandleader welcoming visiting artists to Accra's live scene."},
]

CLASSROOM = {
    "assignments": [
        {"id": "ghana-residency", "title": "Prepare for a Creative Residency in Ghana",
         "destination_id": "ghana", "due": "2026-09-15", "students_total": 18, "students_complete": 11,
         "cover": "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
         "components": [
             {"id": "c1", "label": "Cultural research", "done": True},
             {"id": "c2", "label": "Professional-conduct lesson", "done": True},
             {"id": "c3", "label": "Creative-industry overview", "done": False},
             {"id": "c4", "label": "Language preparation", "done": False},
             {"id": "c5", "label": "Travel checklist", "done": True},
             {"id": "c6", "label": "Reflection submission", "done": False},
         ]},
    ],
    "roster": [
        {"name": "Maya Thompson", "readiness": 72, "missing": ["Visa determination", "Insurance"], "status": "On track"},
        {"name": "Sofia Marín", "readiness": 88, "missing": ["Language prep"], "status": "On track"},
        {"name": "Devon Clarke", "readiness": 41, "missing": ["Passport copy", "Visa", "Cultural course"], "status": "At risk"},
        {"name": "Lena Ortiz", "readiness": 95, "missing": [], "status": "Ready"},
        {"name": "Ravi Patel", "readiness": 60, "missing": ["Insurance", "Reflection"], "status": "On track"},
    ],
    "announcements": [
        {"id": "a1", "title": "Pre-departure orientation", "date": "2026-09-20", "body": "Mandatory orientation covering safety, conduct and logistics. Attendance required."},
    ],
}

CULTURAL_INSIGHTS = [
    {"title": "The Meaning of 'Itadakimasu'", "destination_id": "japan",
     "body": "Before eating, Japanese people say 'itadakimasu' — a humble expression of gratitude to everyone who made the meal possible, from farmers to the cook. It's a small ritual that reflects a culture of mindfulness and respect.",
     "image": "https://images.pexels.com/photos/24205162/pexels-photo-24205162.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
    {"title": "Akwaaba — The Spirit of Welcome", "destination_id": "ghana",
     "body": "In Ghana, 'Akwaaba' means 'welcome' — but it's more than a word. Hospitality is a core value; guests are honored, and sharing food is a sign of trust and community.",
     "image": "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?crop=entropy&cs=srgb&fm=jpg&q=85&w=940"},
]

SAFETY = {
    "trusted_contacts": [
        {"id": "t1", "name": "Denise Thompson", "relationship": "Mother", "phone_masked": "+1 ••• ••• 7734"},
        {"id": "t2", "name": "Prof. Alan Reyes", "relationship": "Program Lead", "phone_masked": "+1 ••• ••• 2210"},
    ],
    "help_options": [
        {"id": "medical", "label": "Medical emergency", "guidance": "Call the local emergency number, then contact your insurer's assistance line and your group leader."},
        {"id": "passport", "label": "Lost passport", "guidance": "Contact your embassy/consulate immediately for an emergency travel document. Have your masked passport record ready."},
        {"id": "legal", "label": "Legal assistance", "guidance": "Contact your embassy for a list of local attorneys. Do not sign documents you don't understand."},
        {"id": "harassment", "label": "Harassment or discrimination", "guidance": "Move to a safe place, document what happened, and contact your group leader or trusted contact for support."},
        {"id": "missing", "label": "Missing team member", "guidance": "Alert your group leader, use group check-in, and contact local authorities if someone is unaccounted for."},
        {"id": "leader", "label": "Contact group leader", "guidance": "Reach your program lead directly through your trip's Team tab."},
        {"id": "emergency-person", "label": "Contact emergency person", "guidance": "Reach your designated emergency contact from your Passport profile."},
        {"id": "embassy", "label": "Embassy or consular support", "guidance": "Locate your nearest embassy/consulate for official assistance."},
    ],
    "resources": [
        {"title": "Lost-document guidance", "body": "Keep masked digital copies in Passport. Report loss to local police and your embassy promptly."},
        {"title": "Medical-support guidance", "body": "Know your destination's emergency number, carry insurance details, and note the nearest hospital."},
        {"title": "Natural-disaster guidance", "body": "Japan: know earthquake protocols — Drop, Cover, Hold On. Identify building evacuation routes on arrival."},
    ],
}
